/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.ayan;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.sql.Timestamp;
import java.util.ArrayDeque;
import java.util.concurrent.ConcurrentHashMap;

@SpringBootApplication
public class TestApplication {


    public static void main(String[] args){
        SpringApplication.run(TestApplication.class,args);
    }
}
